alter table article_stem_count drop constraint article_stem_count_stem_id_fkey;

alter TABLE mean_stem_count drop CONSTRAINT mean_stem_count_stem_id_fkey;

alter table principal_component drop CONSTRAINT principal_component_stem_id_fkey;

